/*
 * Stephen Drollinger
 * Course CMSC335
 * Date: 3/29/2014
 * Project: Project 1
 * File: Library.java
 * Development Enironment Windows 7 Netbeans IDE 7.4 java 1.7.0_45
 */
package Project1;

import java.util.ArrayList;

public class Library<T> implements LibraryInterface<T> {
    // Formal Generic Type: T

    //Container Class: ArrayList
    private ArrayList<T> list = new ArrayList<T>();

    @Override
    public void add(T o) {
        this.list.add(o);
    }

    @Override
    public void delete(T o) {
        this.list.remove(o);
    }

    @Override
    public void checkIn(T o) {
        // AutoGenerated method stub
    }

    @Override
    public void checkOut(T o) {
        // AutoGenerated method stub
    }

    @Override
    public Object[] toArray() {
        Object[] objLibrary = new Object[list.size()];
        for (int i = 0; i < list.size(); i++) {
            System.out.println(list.get(i).toString());
            objLibrary[i] = list.get(i);
        }
        return objLibrary;
    }

    @Override
    public int size() {
        return list.size();
    }

    @Override
    public Object getAtIndex(int i) {
        return this.list.get(i);
    }

    @Override
    public void delteAtIndex(int i) {
        this.list.remove(i);
    }

}
